routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//MIDDLEWARES
Route::middleware(['auth'])->group(function() {
    //Products routes
    Route::resource('productos', 'Producto\ProductoController');

    //Cart routes
    Route::resource('cart', 'Cart\CartController');
    Route::get('addItem/{id}', 'Cart\CartController@addItem')->name('add-item');
    Route::get('clearCart', 'Cart\CartController@clearCart')->name('clear-cart');
    Route::get('addItemsGroup/{items}', 'Cart\CartController@addItemsGroup')->name('add-items-group');

    Route::resource('pedido', 'TBCINV\TBCINVController');
    Route::get('historial_pedidos', 'TBCINV\TBCINVController@historialPedidos')->name('historial-pedidos');
    Route::get('consultar_pedidos', 'TBCINV\TBCINVController@consultarPedidos')->name('consultar-pedidos');

    Route::resource('detalle_pedido', 'TBDINV\TBDINVController');

    //Pdf
    Route::resource('pdf', 'PDF\PdfController');
});

app/Http/Controllers/Cart/CartController.php
<?php

namespace App\Http\Controllers\Cart;

use App\Models\ARBODB;
//use Darryldecode\Cart\Cart;
use App\Models\TBBIM_TIPOCL;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Mockery\CountValidator\Exception;

use Cart;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cartCollection = Cart::getContent();
        $data = array_reverse($cartCollection->toArray());

        return view('cart.index')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->quantity == 0) {
            Cart::remove($id);
            session()->flash('flash_message', '¡Producto eliminado del carrito!');
            session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning
        } else {
            Cart::update($id, array(
                'quantity' => array(
                    'relative' => false,
                    'value' => $request->quantity
                ),
            ));
            session()->flash('flash_message', '¡Cantidad del producto actualizada!');
            session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning
        }

        return response()->json(['success' => true]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Cart::remove($id);

        session()->flash('flash_message', '¡Producto eliminado del carrito!');
        session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning

        return redirect()->route('cart.index');
    }

    public function addItem(Request $request, $id) {
        try {
            $producto = ARBODB::find($id);
            $precio = $this->getPrecioCliente($producto);

             Cart::add(array(
                'id' => $producto->NUMERO_ITEM,
                'name' => $producto->DESCRIPCION,
                'price' => $precio,
                'quantity' =>  $request->cantidad,
                'attributes' => array()
            ));
            session()->flash('flash_message', '¡Producto agregado al carrito!');
            session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning
        } catch (Exception $ex) {
            return view('errors.405');
        } finally {
            return redirect()->route('cart.index');
        }
    }

    public function getPrecioCliente($producto) {
        $cliente = Auth::user();
        $tipoclte = $cliente->TIPOCLTE;
        if ($tipoclte == "0") {
            $tipoclte = "1";
        }

        $nivel_precio_cliente = TBBIM_TIPOCL::find($tipoclte)->TIP_NIVELPRE;
        switch ($nivel_precio_cliente) {
            case 1: {
                return $producto->PRECIOD_VTA_1;
            }
            case 2: {
                return $producto->PRECIOD_VTA_2;
            }
            case 3: {
                return $producto->PRECIOD_VTA_3;
            }
            case 4: {
                return $producto->PRECIOD_VTA_4;
            }
            case 5: {
                return $producto->PRECIOD_VTA_5;
            }
            case 6: {
                return $producto->PRECIOD_VTA_6;
            }
            case 7: {
                return $producto->PRECIOD_VTA_7;
            }
            case 8: {
                return $producto->PRECIOD_VTA_8;
            }
        }
    }

    public function addItemsGroup(Request $request, $items) {
        try {
            $array_items = json_decode($items);

            foreach ($array_items as $item) {
                $producto = ARBODB::find($item->numeroItem);
                $precio = $this->getPrecioCliente($producto);
                Cart::add(array(
                    'id' => $producto->NUMERO_ITEM,
                    'name' => $producto->DESCRIPCION,
                    'price' => $precio,
                    'quantity' =>  $item->cantidad,
                    'attributes' => array()
                ));
            }

            session()->flash('flash_message', '¡Productos agregados al carrito!');
            session()->flash('alert_class', 'alert-success'); //Tambien hay la clase alert-warning
        } catch (Exception $ex) {
            return view('errors.405');
        } finally {
            return redirect()->route('cart.index');
        }
    }

    public function clearCart() {
        Cart::clear();

        return redirect()->route('cart.index');
    }
}

resources/views/cart/index.blade.php
@extends('layouts.app')

@section('title', 'Carrito de compras')

@section('content')
    <div class="container" style="margin-bottom: 22px">
        {{--
        <h1>Tu pedido</h1>
        --}}
        <hr>

        @if (!Cart::isEmpty())
            <div class="row">
                <div class="col-xs-12 col-sm-4 col-md-3">
                    <a href="{{ route('productos.index') }}" class="btn btn-primary btn-lg">Continuar comprando</a> &nbsp;
                </div>
                <div class="col-xs-12 col-sm-4 col-md-3">
                    {!! Form::open(['route' =>  'pedido.store', 'method' => 'POST']) !!}
                    {!! csrf_field() !!}
                    <input type="submit" class="btn btn-success btn-lg" value="Cerrar pedido">
                    {!!Form::close() !!}
                </div>
                <div class="col-xs-12 col-sm-4 col-md-6">
                    <form action="{{ route('clear-cart') }}" method="GET">
                        {!! csrf_field() !!}
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="submit" class="btn btn-danger btn-lg pull-right" value="Vaciar carrito" onclick="return confirm('¿Seguro que desea vaciar carrito de pedido?')">
                    </form>
                </div>
            </div>

            <div class="panel panel-default" >
                <div class="panel-heading" style="font-weight: bold; font-size: 18px;">
                    Tu pedido
                    <a class="pull-right" href="{{route('pdf.index')}}" target="_blank" title="Descargar PDF" style="margin-right: 10px;">
                        <i class="fa fa-download" aria-hidden="true"></i>
                        {{--
                        <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                        --}}
                    </a>
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio unitario</th>
                        <th>Total</th>
                        <th class="column-spacer"></th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($data as $item)
                        <tr>
                            <td width="40%"><a href="{{ route('productos.show', $item['id']) }}">{{ $item['name'] }}</a></td>
                            <td width="20%">
                                <div class="col-xs-12 col-sm-6 col-md-6" style="padding-left: 0px; padding-right: 0px">
                                    {!!Form::number('cantidad', $item['quantity'], ['class' => 'form-control', 'min' => '0','required', 'id' => 'qty-'.$item['id']]) !!}
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-6" style="padding-left: 0px; padding-right: 0px">
                                    <button type="submit" class="btn btn-primary btn-edit" data-id="{{$item['id']}}">
                                        <i class="fa fa-refresh" aria-hidden="true"></i>
                                    </button>
                                </div>
                            </td>
                            <td width="20%">$ {{$item['price']}}</td>
                            <td width="15%">$ {{$item['price'] * $item['quantity']}}</td>
                            <td width="5%">
                                {!! Form::open(['route' =>  ['cart.destroy', $item['id']] , 'method' => 'DELETE']) !!}
                                {!! csrf_field() !!}
                                <input type="submit" class="btn btn-danger btn-sm" value="Eliminar" onclick="return confirm('¿Seguro que desea eliminarlo?')">
                                {!!Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td class="table-image"></td>
                        <td></td>
                        <td class="small-caps table-bg" style="text-align: right">Subtotal</td>
                        <td>$ {{ Cart::getSubtotal() }}</td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr class="border-bottom">
                        <td class="table-image"></td>
                        <td style="padding: 40px;"></td>
                        <td class="small-caps table-bg" style="text-align: right">Total a pagar</td>
                        <td class="table-bg">$ {{ Cart::getTotal() }}</td>
                        <td class="column-spacer"></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        @else
            <h3>No tienes items en tu carrito de compras</h3>
            <a href="{{ route('productos.index') }}" class="btn btn-primary btn-lg">Continuar comprando</a>
        @endif
    </div>
@endsection

@section('extra-js')
    <script>
        (function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $(".btn-edit").click(function(e) {
                var id = $(this).attr('data-id');
                var qty = $('#qty-' + id).val();

                $.ajax({
                    type: "PATCH",
                    url: '{{ url("/cart") }}' + '/' + id,
                    data: {
                        'quantity': qty,
                    },
                    success: function(data) {
                        window.location.href = '{{ url('/cart') }}';
                    }
                });
            });
        })();
    </script>
@endsection